name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t shopping-api .

      - name: List Docker Images
        run: |
          docker images

      - name: Save Docker Image
        run: |
          docker save shopping-api -o shopping-api.tar

      - name: Zip Docker Image
        run: |
          mkdir images

      - name: Copy Docker Image to Images Folder
        run: |
          cp shopping-api.tar images/

      - name: zip Docker image Folder
        run: |
          cd images
          zip -r ../images.zip .

      - name: Verify Files
        run: |
          ls -lh
          ls -lh images

      - name: Upload Docker Zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shopping-api-image
          path: images.zip
