name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t shopping-api .

      - name: Save Docker Image
        run: |
          docker save -o shopping-api.tar shopping-api

      - name: Verify TAR File
        run: |
          ls -lh shopping-api.tar
          file shopping-api.tar

      - name: Create Images Folder
        run: |
          mkdir -p images

      - name: Copy TAR File to Images Folder
        run: |
          cp shopping-api.tar images/

      - name: Verify Images Folder
        run: |
          ls -lh images

      - name: Zip Images Folder
        run: |
          zip -r images.zip images

      - name: Verify ZIP File
        run: |
          ls -lh images.zip

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shopping-api-image
          path: images.zip
