name: Docker CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: shoppingcartapi

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository owner to lowercase
        id: owner
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ steps.owner.outputs.owner }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ steps.owner.outputs.owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Save Docker Image
        run: |
          docker save ghcr.io/${{ steps.owner.outputs.owner }}/${{ env.IMAGE_NAME }}:latest -o shoppingcartapi.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shoppingcartapi-image
          path: shoppingcartapi.tar
